server:
  port: 8080
cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
file:
  upload-dir: /uploadedFiles
springdoc:
  pathsToMarch:
    - /auth/**
    - /api/**
  swagger-ui:
    enabled: true
    use-root-path: true
  api-docs:
    enabled: true
security:
  jwt:
    token:
      expire-length: 3600000 #1h
    key:
      public: classpath:app.pub
      private: classpath:app.key

spring:
  application.name: rest-with-spring-boot-and-java-erudio
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
        #properties:
      #hibernate:
      #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Desabilitar linhas abaixo caso opte por usar algum perfil específico
    url: jdbc:mysql://spring-foundation.c1ci8w8869ni.us-east-2.rds.amazonaws.com:3306/spring_foundation?useTimezone=true&serverTimezone=UTC
    username: docker
    password: adminadmin

#Configurações de base de dados por perfil
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://spring-foundation.c1ci8w8869ni.us-east-2.rds.amazonaws.com:3306/spring_foundation?useTimezone=true&serverTimezone=UTC
    username: docker
    password: adminadmin

---

spring:
  config:
    activate:
      on-profile: dev-home
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin

---

spring:
  config:
    activate:
      on-profile: dev-senior
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
