name: CI/CD with Github Actions

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to do Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./rest-with-spring-boot-and-java-erudio
      run: mvn -B package --file pom.xml -DskipTests

    - name: Docker Compose build
      working-directory: ./
      run: docker compose build

    - name: Tag, and push docker image to Amazon ECR
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/spring-foundation:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.RUN_ID }}
        docker tag ${{ secrets.DOCKER_USERNAME }}/spring-foundation:latest ${{ secrets.IMAGE_REPO_URL }}:latest
        docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.RUN_ID }}
        docker push ${{ secrets.IMAGE_REPO_URL }}:latest

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/spring-foundation:latest ${{ secrets.DOCKER_USERNAME }}/spring-foundation:${{ github.RUN_ID }} 
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-foundation:${{ github.RUN_ID }}
        docker push ${{ secrets.DOCKER_USERNAME }}/spring-foundation:latest
